cta:
  bucket: null
  version: null
  domain: null
name: Testing Grounds
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.482384268892929
color:
  saturation: 0.8440861
  brandStrength: 0.5099939841311425
  lightness: 0.7258065
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 0.669147
layout_spectrum: 0.9775100704282522
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
